// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import ThemeContextProvider from "@/theme/ThemeContextProvider";
import ProtectedRoute from "@/components/auth/ProtectedRoute";
import AppFrame from "@/components/layout/AppFrame";
import FrontendErrorBoundary from "@/components/platform/FrontendErrorBoundary";
import FrontendErrorReporter from "@/components/platform/FrontendErrorReporter";
import { AuthContextProvider } from "@/context/AuthContext";
import { SubscriptionContextProvider } from "@/context/SubscriptionContext";
import "./globals.css";

export const metadata = {
  title: "Infomentica DSS Enterprise",
  description: "Enterprise AI Decision Support System",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <AuthContextProvider>
            <SubscriptionContextProvider>
              <ProtectedRoute>
                <FrontendErrorBoundary>
                  <FrontendErrorReporter />
                  <AppFrame>{children}</AppFrame>
                </FrontendErrorBoundary>
              </ProtectedRoute>
            </SubscriptionContextProvider>
          </AuthContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
