from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any


FREELANCER_MOCK_FIXTURE_VERSION = "2026.08.09"


def _project(
    project_id: str,
    title: str,
    description: str,
    *,
    budget_min: float | None,
    budget_max: float | None,
    currency: str,
    project_type: str,
    bid_count: int,
    hours_ago: int,
    client_username: str,
    client_country: str,
    client_city: str,
    payment_verified: bool,
    skills: list[dict[str, Any]],
    rating: float | None = None,
    review_count: int | None = None,
    posted_count: int | None = None,
    completed_count: int | None = None,
    status: str = "active",
) -> dict[str, Any]:
    now = datetime.now(timezone.utc)
    submitted = now - timedelta(hours=hours_ago)
    return {
        "id": project_id,
        "title": title,
        "description": description,
        "preview_description": description[:240],
        "seo_url": f"/projects/software/{project_id.lower()}",
        "type": project_type,
        "status": status,
        "time_submitted": int(submitted.timestamp()),
        "time_updated": int((submitted + timedelta(hours=1)).timestamp()),
        "submitdate": int((submitted + timedelta(days=5)).timestamp()),
        "budget": {"minimum": budget_min, "maximum": budget_max},
        "currency": {"code": currency},
        "bid_stats": {"bid_count": bid_count, "bid_avg": budget_min or budget_max or 0},
        "jobs": skills,
        "owner": {
            "username": client_username,
            "payment_verified": payment_verified,
            "reputation": rating,
            "reviews": review_count,
            "jobs_posted_count": posted_count,
            "jobs_completed_count": completed_count,
            "location": {
                "country": {"name": client_country},
                "city": {"name": client_city},
            },
        },
    }


def freelancer_mock_projects() -> list[dict[str, Any]]:
    return [
        _project(
            "FRL-MOCK-1001",
            "Build Document Approval Workflow Platform",
            "Need a React, Python and PostgreSQL workflow platform for document approvals, role-based routing, audit history and API integrations.",
            budget_min=3000,
            budget_max=5000,
            currency="USD",
            project_type="fixed",
            bid_count=5,
            hours_ago=6,
            client_username="acme-operations",
            client_country="Saudi Arabia",
            client_city="Riyadh",
            payment_verified=True,
            rating=4.8,
            review_count=21,
            posted_count=18,
            completed_count=11,
            skills=[
                {"id": 1, "name": "React.js", "category": {"name": "Web Development"}},
                {"id": 2, "name": "Python", "category": {"name": "Software Architecture"}},
                {"id": 3, "name": "PostgreSQL", "category": {"name": "Databases"}},
                {"id": 4, "name": "API", "category": {"name": "Software Architecture"}},
                {"id": 5, "name": "Workflow", "category": {"name": "Business Analysis"}},
            ],
        ),
        _project(
            "FRL-MOCK-1002",
            "Develop AI-Powered Inspection Management System",
            "Build an inspection management system with FastAPI, AI classification, React dashboards and audit-ready reporting for field inspections.",
            budget_min=5000,
            budget_max=8000,
            currency="USD",
            project_type="fixed",
            bid_count=4,
            hours_ago=10,
            client_username="quality-audit-group",
            client_country="United Arab Emirates",
            client_city="Dubai",
            payment_verified=True,
            rating=4.9,
            review_count=34,
            posted_count=22,
            completed_count=16,
            skills=[
                {"id": 6, "name": "FastAPI", "category": {"name": "Software Architecture"}},
                {"id": 7, "name": "Artificial Intelligence", "category": {"name": "AI"}},
                {"id": 8, "name": "React.js", "category": {"name": "Web Development"}},
                {"id": 9, "name": "Python", "category": {"name": "Software Architecture"}},
            ],
        ),
        _project(
            "FRL-MOCK-1003",
            "Build Business Intelligence Dashboard",
            "Looking for a developer to create analytics dashboards, KPI reporting and role-based exports using Python APIs and React.",
            budget_min=2200,
            budget_max=4200,
            currency="USD",
            project_type="fixed",
            bid_count=8,
            hours_ago=14,
            client_username="insight-manufacturing",
            client_country="Qatar",
            client_city="Doha",
            payment_verified=True,
            rating=4.5,
            review_count=12,
            posted_count=14,
            completed_count=8,
            skills=[
                {"id": 10, "name": "Data Analytics", "category": {"name": "Analytics"}},
                {"id": 11, "name": "React.js", "category": {"name": "Web Development"}},
                {"id": 12, "name": "Python", "category": {"name": "Software Architecture"}},
            ],
        ),
        _project(
            "FRL-MOCK-1004",
            "API Integration Between ERP and Web Portal",
            "Need API integration between ERP, customer portal and approval workflow. Experience with APIs, .NET or Python preferred.",
            budget_min=2500,
            budget_max=4500,
            currency="USD",
            project_type="fixed",
            bid_count=7,
            hours_ago=18,
            client_username="erp-bridge",
            client_country="United Kingdom",
            client_city="London",
            payment_verified=True,
            rating=4.6,
            review_count=18,
            posted_count=12,
            completed_count=9,
            skills=[
                {"id": 13, "name": "API", "category": {"name": "Software Architecture"}},
                {"id": 14, "name": ".NET", "category": {"name": "Software Architecture"}},
                {"id": 15, "name": "Python", "category": {"name": "Software Architecture"}},
                {"id": 16, "name": "Integration", "category": {"name": "Business Analysis"}},
            ],
        ),
        _project(
            "FRL-MOCK-1005",
            "Custom Internal Employee Portal",
            "Employee self-service portal with forms, internal requests, authentication and document repository. Remote contractor preferred.",
            budget_min=1800,
            budget_max=3200,
            currency="USD",
            project_type="hourly",
            bid_count=12,
            hours_ago=30,
            client_username="hr-portal-team",
            client_country="India",
            client_city="Bengaluru",
            payment_verified=False,
            rating=4.0,
            review_count=6,
            posted_count=10,
            completed_count=4,
            skills=[
                {"id": 17, "name": "Portal", "category": {"name": "Web Development"}},
                {"id": 18, "name": "React.js", "category": {"name": "Web Development"}},
                {"id": 19, "name": "Authentication", "category": {"name": "Software Architecture"}},
            ],
        ),
        _project(
            "FRL-MOCK-1006",
            "WordPress customization for marketing site",
            "Small WordPress theme customization and landing-page tweaks for campaigns.",
            budget_min=300,
            budget_max=700,
            currency="USD",
            project_type="fixed",
            bid_count=19,
            hours_ago=12,
            client_username="brand-refresh",
            client_country="United States",
            client_city="Austin",
            payment_verified=True,
            skills=[
                {"id": 20, "name": "WordPress", "category": {"name": "CMS"}},
                {"id": 21, "name": "CSS", "category": {"name": "Web Development"}},
            ],
        ),
        _project(
            "FRL-MOCK-1007",
            "Logo Design for Startup Launch",
            "Need logo design, brochure and social-media branding pack.",
            budget_min=150,
            budget_max=300,
            currency="USD",
            project_type="fixed",
            bid_count=27,
            hours_ago=20,
            client_username="launch-kit",
            client_country="Canada",
            client_city="Toronto",
            payment_verified=False,
            skills=[
                {"id": 22, "name": "Logo Design", "category": {"name": "Graphic Design"}},
                {"id": 23, "name": "Photoshop", "category": {"name": "Graphic Design"}},
            ],
        ),
        _project(
            "FRL-MOCK-1008",
            "Instagram SEO Promotion Campaign",
            "Need social media posting, hashtags, backlinks and Instagram SEO promotion for 30 days.",
            budget_min=100,
            budget_max=250,
            currency="USD",
            project_type="fixed",
            bid_count=31,
            hours_ago=8,
            client_username="growth-social",
            client_country="Egypt",
            client_city="Cairo",
            payment_verified=False,
            skills=[
                {"id": 24, "name": "SEO", "category": {"name": "Marketing"}},
                {"id": 25, "name": "Social Media Marketing", "category": {"name": "Marketing"}},
            ],
        ),
        _project(
            "FRL-MOCK-1009",
            "Manual Data Entry and Spreadsheet Cleanup",
            "Copy-paste data entry into spreadsheets and basic cleanup.",
            budget_min=80,
            budget_max=180,
            currency="USD",
            project_type="fixed",
            bid_count=44,
            hours_ago=16,
            client_username="ops-admin-work",
            client_country="Pakistan",
            client_city="Lahore",
            payment_verified=False,
            skills=[
                {"id": 26, "name": "Data Entry", "category": {"name": "Admin Support"}},
                {"id": 27, "name": "Excel", "category": {"name": "Admin Support"}},
            ],
        ),
        _project(
            "FRL-MOCK-1010",
            "French document workflow modernization",
            "Nous recherchons un developpeur Python et React pour moderniser un systeme de gestion documentaire, workflow d'approbation et tableaux de bord.",
            budget_min=2600,
            budget_max=4100,
            currency="EUR",
            project_type="fixed",
            bid_count=6,
            hours_ago=9,
            client_username="marseille-docs",
            client_country="France",
            client_city="Marseille",
            payment_verified=True,
            rating=4.7,
            review_count=10,
            posted_count=9,
            completed_count=5,
            skills=[
                {"id": 28, "name": "Python", "category": {"name": "Software Architecture"}},
                {"id": 29, "name": "React.js", "category": {"name": "Web Development"}},
                {"id": 30, "name": "Gestion documentaire", "category": {"name": "Business Analysis"}},
            ],
        ),
        _project(
            "FRL-MOCK-1011",
            "Case Management Portal for Compliance Team",
            "Create a case-management portal with approvals, search, dashboards and audit tracking. Open to hourly contractors.",
            budget_min=45,
            budget_max=70,
            currency="USD",
            project_type="hourly",
            bid_count=9,
            hours_ago=26,
            client_username="compliance-cases",
            client_country="Germany",
            client_city="Berlin",
            payment_verified=True,
            rating=4.4,
            review_count=13,
            posted_count=11,
            completed_count=7,
            skills=[
                {"id": 31, "name": "Case Management", "category": {"name": "Business Analysis"}},
                {"id": 32, "name": "Next.js", "category": {"name": "Web Development"}},
                {"id": 33, "name": "API", "category": {"name": "Software Architecture"}},
            ],
        ),
        _project(
            "FRL-MOCK-1012",
            "Enterprise Records Archive Migration",
            "Need contractor for records archive migration, metadata mapping, search APIs and reporting exports.",
            budget_min=2800,
            budget_max=5200,
            currency="GBP",
            project_type="fixed",
            bid_count=11,
            hours_ago=40,
            client_username="records-archive",
            client_country="United Kingdom",
            client_city="Manchester",
            payment_verified=True,
            rating=4.7,
            review_count=24,
            posted_count=19,
            completed_count=14,
            skills=[
                {"id": 34, "name": "API", "category": {"name": "Software Architecture"}},
                {"id": 35, "name": "PostgreSQL", "category": {"name": "Databases"}},
                {"id": 36, "name": "Data Migration", "category": {"name": "Databases"}},
            ],
        ),
    ]
