"""Sprint 8H-A connector sync foundation.

This revision is intentionally a no-op compatibility checkpoint.

Earlier autogenerated versions of this migration tried to convert existing
connector tables from UUID primary keys to string primary keys. That does not
match this codebase, which already uses string identifiers in the SQLAlchemy
models and may have databases that were stamped to this revision before the
migration file was corrected.
"""

from typing import Sequence, Union


revision: str = "13bf198836cf"
down_revision: Union[str, Sequence[str], None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
